version: '3.8'
services:
  app:
    container_name: todo-list-app
    restart: always
    build: .
    ports:
      - "8000:3000"
    external_links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ajeetraina
      MONGO_INITDB_ROOT_PASSWORD: ajeetraina123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ajeetraina
      ME_CONFIG_MONGODB_ADMINPASSWORD: ajeetraina123
      ME_CONFIG_MONGODB_URL: mongodb://ajeetraina:ajeetraina123@mongo:27017/

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
