services:
  app:
    image: node:21-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    profiles: ["prod", "dev"]

  mysql:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    profiles: ["dev"]

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ajeetraina
      MONGO_INITDB_ROOT_PASSWORD: ajeetraina123
    profiles: ["prod"]
